export const ERROR_ACCOUNT_NOT_ACTIVATED: string = 'ERROR_ACCOUNT_NOT_ACTIVATED';
export const ERROR_USER_NOT_FOUND: string = 'ERROR_USER_NOT_FOUND';
export const ERROR_DUPLICATE_EMAIL: string = 'ERROR_DUPLICATE_EMAIL';
export const ERROR_NOT_AUTHENTICATED: string = 'ERROR_NOT_AUTHENTICATED';
export const ERROR_NOT_SPECIFIED: string = 'ERROR_NOT_SPECIFIED';
export const ERROR_TOKEN_EXPIRED: string = 'ERROR_TOKEN_EXPIRED';
export const ERROR_WRONG_CREDENTIALS: string = 'ERROR_WRONG_CREDENTIALS';
