name: Push on master
on:
  push:
    branches:
      - master

jobs:
  generate-readme:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      #     registry-url: 'https://registry.npmjs.org'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn install
          yarn build:doc
          yarn badges
          git add .
          git commit -m "generated README.md"
          git push origin master
